name: Manual Expo Android Local Build

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "Select build type"
        required: true
        type: choice
        options:
          - apk

      # environment:
      #   description: "Select environment"
      #   required: true
      #   type: choice
      #   options:
      #     - dev
      #     - stage
      #     - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # - name: Create env file
      #   run: |
      #     if [ "${{ inputs.environment }}" = "dev" ]; then
      #       echo "BASE_SHARE=https://dev.blueoceansteels.com" >> .env
      #       echo "BASE_URL=https://devapi.blueoceansteels.com" >> .env
      #     elif [ "${{ inputs.environment }}" = "stage" ]; then
      #       echo "BASE_SHARE=https://stage.blueoceansteels.com" >> .env
      #       echo "BASE_URL=https://stageapi.blueoceansteels.com" >> .env
      #     else
      #       echo "BASE_SHARE=https://live.blueoceansteels.com" >> .env
      #       echo "BASE_URL=https://prodapi.blueoceansteels.com" >> .env
      #     fi
      #     echo "WEB_URL_LINK=https://app.blueoceansteels.com" >> .env

      # - name: Debug env
      #   run: cat .env

      - name: Expo prebuild (Android)
        run: |
          npx expo prebuild --platform android --non-interactive

      - name: Build APK locally
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          # name: expo-${{ inputs.environment }}-apk
          name: expo-test-apk
          path: android/app/build/outputs/apk/release/*.apk
